name: Build & Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.cpp'
      - '**.h'
      - 'CMakeLists.txt'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up environment
        run: |
          echo "BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
          
          sudo apt update
          sudo apt install -y cmake libboost-system-dev libcurl4-openssl-dev libgtest-dev libssl-dev libsqlite3-dev

      - name: Install gtest
        run: |
          cd /usr/src/gtest
          sudo cmake CmakeLists.txt
          sudo make
          sudo cp ./lib/*.a /usr/lib/

      - name: Build with cmake
        uses: threeal/cmake-action@main

      - name: Run Test
        run: ./*_test
        working-directory: ${{ env.BRANCH_NAME }}
