name: Linters & Formatters

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.cpp'
      - '**.h'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          echo "BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
  
          sudo apt update
          sudo apt install -y clang-format cppcheck

      - name: Install cpplint
        run: |
          python3 -m pip install --upgrade pip
          pip3 install cpplint

      - name: Check code format with clang-format
        run: find . -not -path "./lib/*" \( -iname "*.h" -o -iname "*.cpp" \) -print0 | xargs clang-format -i --Werror
        working-directory: ${{ env.BRANCH_NAME }}

      - name: Check with cpplint
        run: cpplint --exclude=lib/ --filter=-legal/copyright,-build/include_subdir --recursive .
        working-directory: ${{ env.BRANCH_NAME }}

      - name: Check with cppcheck
        run: cppcheck --std=c++20 -i lib .
        working-directory: ${{ env.BRANCH_NAME }}
